### ISSUE TITLE
can you add the link to the game?

### ISSUE THREAD

**Issue by fisx** [michibo/fabulation#1]
you just showed a game at https://www.meetup.com/Berlin-Hack-and-Tell/events/247115229/ that i want to play now!  could you please add the link to the README?  or the yaml file to the repo?  or where can i buy it?  :-)

thanks!

**Comment by benmaier** [comment]
apparently fixed in 18bfa38 :)

**Comment by fisx** [comment]
Excellent, thanks @michibo!  (-:
